// App entry point — Firebase init, Provider tree, AuthService session restore (Phase 11, CG11).
//
// Bootstrap sequence:
//   1. Firebase.initializeApp()
//   2. AuthService.initialize(api) — loads host URL from SharedPreferences,
//      configures ApiClient (Dio + PersistCookieJar), calls GET /setup +
//      GET /auth/me to restore session.
//   3. buildRouter(auth) — GoRouter with redirect guard tied to AuthService.
//   4. PushService.initialize(api) — registers FCM token with backend.
//   5. runApp with Provider tree.
//
// firebase_options.dart is generated by the FlutterFire CLI:
//   flutter pub global activate flutterfire_cli && flutterfire configure
// Until generated, Firebase init is skipped gracefully (push unavailable).

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import 'app.dart';
import 'services/api_client.dart';
import 'services/auth_service.dart';
import 'services/push_service.dart';

// Uncomment after running `flutterfire configure`:
// import 'firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialise Firebase.  Fails gracefully if not yet configured.
  try {
    // Replace with:
    //   await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
    // after running `flutterfire configure`.
    await Firebase.initializeApp();
  } catch (_) {
    // Firebase not configured — push notifications unavailable; rest of app works.
  }

  final api = ApiClient();
  final auth = AuthService();

  // auth.initialize() wires api.onRefresh + api.onLogout, configures Dio, and
  // restores the session from PersistCookieJar.
  await auth.initialize(api);

  // Build the router after auth initializes so the initial redirect is evaluated
  // with the correct isAuthenticated + needsSetup state.
  final router = buildRouter(auth);

  // Wire push deep-link navigation now that router exists.
  final push = PushService();
  push.onNavigate = (route) => router.go(route);

  // Start push service if the backend is reachable (host URL is configured).
  if (api.isConfigured) {
    push.initialize(api).catchError((_) {
      // Non-critical — push won't work but app continues normally.
    });
  }

  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider.value(value: api),
        ChangeNotifierProvider.value(value: auth),
        Provider.value(value: push),
      ],
      child: SentinelApp(router: router),
    ),
  );
}
